In [1]:
import torch

In [2]:
tensor1 = torch.Tensor([[1,2,3], [4,5,6]])
tensor1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [3]:
tensor2 = torch.Tensor([[7,8,9],[10,11,12]])
tensor2

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [4]:
tensor1.requires_grad

False

In [6]:
tensor2.requires_grad

False

In [7]:
tensor1.requires_grad_()

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [8]:
tensor1.requires_grad

True

In [9]:
print(tensor1.grad)

None


In [10]:
print(tensor1.grad_fn)

None


In [11]:
output_tensor = tensor1 * tensor2

In [12]:
output_tensor.requires_grad

True

In [13]:
# No backwards pass made yet
print(output_tensor.grad)

None


In [14]:
print(output_tensor.grad_fn)

In [15]:
print(tensor1.grad_fn)

None


In [16]:
print(tensor2.grad_fn)

None


In [18]:
output_tensor = (tensor1 * tensor2).mean()
print(output_tensor.grad_fn)

In [19]:
print(tensor1.grad)

None


In [20]:
output_tensor.backward()

In [21]:
print(tensor1.grad)

tensor([[1.1667, 1.3333, 1.5000],
        [1.6667, 1.8333, 2.0000]])


In [22]:
tensor1.grad.shape, tensor1.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [23]:
print(tensor2.grad)

None


In [24]:
print(output_tensor.grad)

None


In [25]:
new_tensor = tensor1 * 3
print(new_tensor.requires_grad)

True


In [26]:
new_tensor

tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]], grad_fn=<MulBackward0>)

In [27]:
# Temporarily disable grad
with torch.no_grad():
    new_tensor = tensor1 * 3
    
    print('new_tensor = ', new_tensor)
    
    print('requires_grade for tensor = ', tensor1.requires_grad)
    print('requires_grade for tensor = ', tensor2.requires_grad)
    
    print('requires_grad for new_tensor = ', new_tensor.requires_grad)

new_tensor =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]])
requires_grade for tensor =  True
requires_grade for tensor =  False
requires_grad for new_tensor =  False


In [28]:
def calculate(t):
    return t * 2

In [29]:
@torch.no_grad()
def calculate_with_not_grad(t):
    return t * 2

In [31]:
result_tensor = calculate(tensor1)
result_tensor

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], grad_fn=<MulBackward0>)

In [32]:
result_tensor.requires_grad

True

In [33]:
result_tensor_no_grad = calculate_with_not_grad(tensor1)
result_tensor_no_grad

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [34]:
result_tensor_no_grad.requires_grad

False

In [35]:
with torch.no_grad():
    
    new_tensor_no_grad = tensor1 * 3
    
    print('new_tensor_no_grad = ', new_tensor_no_grad)
    
    with torch.enable_grad():
        
        new_tensor_grad = tensor1 * 3
        
        print('new_tensor_grad = ', new_tensor_grad)

new_tensor_no_grad =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]])
new_tensor_grad =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]], grad_fn=<MulBackward0>)
