In [1]:
import numpy as np
import torch

In [2]:
tensor = torch.rand(4,3)
tensor

tensor([[0.6350, 0.4410, 0.2838],
        [0.7721, 0.5977, 0.6377],
        [0.7089, 0.7577, 0.3900],
        [0.0360, 0.4919, 0.3930]])

In [3]:
type(tensor)

torch.Tensor

In [4]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([[0.6350202 , 0.44103462, 0.28381342],
       [0.7720575 , 0.59770226, 0.6377054 ],
       [0.7089409 , 0.75771165, 0.39003736],
       [0.03598821, 0.49191266, 0.39299965]], dtype=float32)

In [5]:
type(numpy_from_tensor)

numpy.ndarray

In [6]:
torch.is_tensor(tensor)

True

In [7]:
torch.is_tensor(numpy_from_tensor)

False

In [8]:
# Numpy array and PyTorch tensor share the SAME underlying memory

numpy_from_tensor[0,0] = 100.0
numpy_from_tensor

array([[1.0000000e+02, 4.4103462e-01, 2.8381342e-01],
       [7.7205747e-01, 5.9770226e-01, 6.3770539e-01],
       [7.0894092e-01, 7.5771165e-01, 3.9003736e-01],
       [3.5988212e-02, 4.9191266e-01, 3.9299965e-01]], dtype=float32)

In [9]:
tensor

tensor([[1.0000e+02, 4.4103e-01, 2.8381e-01],
        [7.7206e-01, 5.9770e-01, 6.3771e-01],
        [7.0894e-01, 7.5771e-01, 3.9004e-01],
        [3.5988e-02, 4.9191e-01, 3.9300e-01]])

In [10]:
numpy_arr = np.array([[1.0, 2.0, 3.0],
                     [10.0, 20.0, 30.0],
                     [100.0, 200.0, 300.0]])
numpy_arr

array([[  1.,   2.,   3.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [11]:
tensor_from_numpy = torch.from_numpy(numpy_arr)
tensor_from_numpy

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [12]:
type(tensor_from_numpy)

torch.Tensor

In [13]:
torch.is_tensor(tensor_from_numpy)

True

In [15]:
tensor_from_numpy[0] = 1
tensor_from_numpy

tensor([[  1.,   1.,   1.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [16]:
numpy_arr

array([[  1.,   1.,   1.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [17]:
np_array_one = np.array([4,8])

In [18]:
# Performs a copy if the data is not already a tensor. Here, since we are not changing the data type or device
# the NEW tensor will just use the same memory
tensor_from_array_one = torch.as_tensor(np_array_one)
tensor_from_array_one
# If the data is already a tensor with the same dtype and the device then NO COPY is performed and a new tensor
# is returned with the SAME COMPUTATIONAL GRAPH

tensor([4, 8])

In [20]:
np_array_one[1] = 5
np_array_one

array([4, 5])

In [21]:
tensor_from_array_one

tensor([4, 5])

In [24]:
# to Force a copy into a Tensor
np_array_two = np.array([2,2])
tensor_from_array_two = torch.tensor(np_array_two)
tensor_from_array_two

tensor([2, 2])

In [25]:
np_array_two[1] = 4
np_array_two

array([2, 4])

In [26]:
tensor_from_array_two

tensor([2, 2])