In [1]:
import torch
print(torch.__version__)

1.4.0


In [2]:
torch.get_default_dtype()

torch.float32

In [3]:
# torch.set_default_dtype(torch.int)

In [4]:
torch.set_default_dtype(torch.float64)

In [5]:
torch.get_default_dtype()

torch.float64

In [6]:
#https://pytorch.org/docs/stable/tensors.html

In [7]:
tensor_arr = torch.Tensor([[1,2,3], [4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [8]:
torch.is_tensor(tensor_arr)

True

In [9]:
torch.numel(tensor_arr)

6

In [10]:
tensor_initialized = torch.rand(2,2)
tensor_initialized

tensor([[0.3469, 0.5941],
        [0.4354, 0.7062]])

In [11]:
tensor_int = torch.tensor([5, 3]).type(torch.IntTensor)
tensor_int

tensor([5, 3], dtype=torch.int32)

In [12]:
tensor_short = torch.ShortTensor([1.0, 2.0, 3.0])
tensor_short

tensor([1, 2, 3], dtype=torch.int16)

In [13]:
tensor_fill = torch.full((2,6), fill_value=10)
tensor_fill

tensor([[10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10.]])

In [14]:
tensors_of_ones = torch.ones([2,4], dtype=torch.int32)
tensors_of_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [15]:
tensor_of_zeroes = torch.zeros_like(tensors_of_ones)
tensor_of_zeroes

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [16]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [17]:
torch.nonzero(torch.eye(5))

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [18]:
# makes a copy of the underlying data of the tensor
i = torch.tensor([[0,1,1],[2,2,0]])

In [19]:
v = torch.tensor([3,4,5], dtype=torch.float32)

In [20]:
sparse_tensor = torch.sparse_coo_tensor(i, v, [2,5])
sparse_tensor.data

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)

In [21]:
initial_tensor = torch.rand(2,3)
initial_tensor

tensor([[0.7965, 0.8321, 0.3270],
        [0.8142, 0.2623, 0.7910]])

In [22]:
initial_tensor.fill_(10)

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [23]:
new_tensor = initial_tensor.add(5)
new_tensor, initial_tensor

(tensor([[15., 15., 15.],
         [15., 15., 15.]]),
 tensor([[10., 10., 10.],
         [10., 10., 10.]]))

In [24]:
initial_tensor.add_(8)
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [25]:
x = torch.linspace(start=0.1, end=10.0, steps=15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [26]:
tensor_chunk = torch.chunk(x, 3, 0)
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [27]:
tensor1 = tensor_chunk[0]
tensor2 = tensor_chunk[1]
tensor3 = torch.tensor([3.0, 4.0, 5.0])
torch.cat((tensor1, tensor2, tensor3), 0)

tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [28]:
random_tensor = torch.Tensor([[10, 8, 30], [40, 5, 6], [12, 2, 21]])
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [29]:
random_tensor[0, 1]

tensor(8.)

In [30]:
random_tensor[1:,1:]

tensor([[ 5.,  6.],
        [ 2., 21.]])

In [31]:
random_tensor.size()

torch.Size([3, 3])

In [32]:
resized_tensor = random_tensor.view(9)
resized_tensor

tensor([10.,  8., 30., 40.,  5.,  6., 12.,  2., 21.])

In [33]:
random_tensor.view(-1)

tensor([10.,  8., 30., 40.,  5.,  6., 12.,  2., 21.])

In [34]:
random_tensor.view(3,-1)

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [35]:
random_tensor[2,2] = 100.0
resized_tensor

tensor([ 10.,   8.,  30.,  40.,   5.,   6.,  12.,   2., 100.])

In [36]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [37]:
random_tensor.shape

torch.Size([3, 3])

In [38]:
tensor_unsqueeze = torch.unsqueeze(random_tensor, 2)
tensor_unsqueeze

tensor([[[ 10.],
         [  8.],
         [ 30.]],

        [[ 40.],
         [  5.],
         [  6.]],

        [[ 12.],
         [  2.],
         [100.]]])

In [39]:
tensor_unsqueeze.shape

torch.Size([3, 3, 1])

In [40]:
torch.unsqueeze(random_tensor, 1)

tensor([[[ 10.,   8.,  30.]],

        [[ 40.,   5.,   6.]],

        [[ 12.,   2., 100.]]])

In [41]:
torch.unsqueeze(random_tensor, 0)

tensor([[[ 10.,   8.,  30.],
         [ 40.,   5.,   6.],
         [ 12.,   2., 100.]]])

In [42]:
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [44]:
tensor_transpose = torch.transpose(initial_tensor, 0, 1)
tensor_transpose

tensor([[18., 18.],
        [18., 18.],
        [18., 18.]])

In [45]:
sorted_tensor, sorted_indices = torch.sort(random_tensor)

In [46]:
sorted_tensor

tensor([[  8.,  10.,  30.],
        [  5.,   6.,  40.],
        [  2.,  12., 100.]])

In [47]:
sorted_indices

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

In [48]:
tensor_float = torch.FloatTensor([-1.1, -2.2, 3.3])
tensor_float

tensor([-1.1000, -2.2000,  3.3000], dtype=torch.float32)

In [49]:
tensor_abs = torch.abs(tensor_float)
tensor_abs

tensor([1.1000, 2.2000, 3.3000], dtype=torch.float32)

In [50]:
rand1 = torch.abs(torch.randn(2,3))
rand2 = torch.abs(torch.randn(2,3))

In [52]:
rand1 + rand2

tensor([[1.5009, 0.5150, 0.2861],
        [2.6667, 2.3180, 2.0826]])

In [53]:
torch.add(rand1, rand2)

tensor([[1.5009, 0.5150, 0.2861],
        [2.6667, 2.3180, 2.0826]])

In [54]:
tensor = torch.Tensor([[-1, -2, -3], [1, 2, 3]])

In [55]:
torch.div(tensor, tensor+0.3)

tensor([[1.4286, 1.1765, 1.1111],
        [0.7692, 0.8696, 0.9091]])

In [57]:
tensor_mul = torch.mul(tensor, tensor)
tensor_mul

tensor([[1., 4., 9.],
        [1., 4., 9.]])

In [58]:
torch.clamp(tensor, min=-0.2, max=2)

tensor([[-0.2000, -0.2000, -0.2000],
        [ 1.0000,  2.0000,  2.0000]])

In [59]:
t1 = torch.Tensor([1,2])
t2 = torch.Tensor([10,20])

In [60]:
torch.dot(t1, t2)

tensor(50.)

In [61]:
matrix = torch.Tensor([[1,2,3],[4,5,6]])
vector = torch.Tensor([0,1,2])

In [62]:
# matrix multiply with vector
torch.mv(matrix, vector)

tensor([ 8., 17.])

In [63]:
another_matrix = torch.Tensor([[10, 30], [20,0], [0,50]])

In [66]:
torch.mm(matrix, another_matrix)

tensor([[ 50., 180.],
        [140., 420.]])

In [67]:
#find the largest value location in a matrix in the dim
torch.argmax(another_matrix, dim=1)

tensor([1, 0, 1])

In [69]:
torch.argmax(another_matrix, dim=0)

tensor([1, 2])

In [70]:
torch.argmin(another_matrix, dim=0)

tensor([2, 1])