In [1]:
import torch
import pandas as pd
iris_main = pd.read_csv('https://raw.githubusercontent.com/pandas-dev/pandas/master/pandas/tests/data/iris.csv')

In [2]:
iris = iris_main.copy()
iris.dtypes

SepalLength    float64
SepalWidth     float64
PetalLength    float64
PetalWidth     float64
Name            object
dtype: object

In [3]:
iris.sample(10)

SepalLength  SepalWidth  PetalLength  PetalWidth             Name
58           6.6         2.9          4.6         1.3  Iris-versicolor
118          7.7         2.6          6.9         2.3   Iris-virginica
82           5.8         2.7          3.9         1.2  Iris-versicolor
10           5.4         3.7          1.5         0.2      Iris-setosa
73           6.1         2.8          4.7         1.2  Iris-versicolor
52           6.9         3.1          4.9         1.5  Iris-versicolor
44           5.1         3.8          1.9         0.4      Iris-setosa
1            4.9         3.0          1.4         0.2      Iris-setosa
53           5.5         2.3          4.0         1.3  Iris-versicolor
147          6.5         3.0          5.2         2.0   Iris-virginica

In [10]:
value_count_output = iris['Name'].value_counts()
value_count_output.to_dict(), value_count_output.min()

({'Iris-setosa': 50, 'Iris-virginica': 50, 'Iris-versicolor': 50}, 50)

In [33]:
my_num = 2
a = iris[iris['Name'] == 'Iris-setosa'].sample(my_num)
b = iris[iris['Name'] == 'Iris-virginica'].sample(my_num)
c = iris[iris['Name'] == 'Iris-versicolor'].sample(my_num)

In [40]:
iris_train_df = pd.concat([a,b,c]).copy()
# iris_train_df = pd.concat([a,b,c]).sample(frac=1).copy()
iris_train_df

SepalLength  SepalWidth  PetalLength  PetalWidth             Name
39           5.1         3.4          1.5         0.2      Iris-setosa
29           4.7         3.2          1.6         0.2      Iris-setosa
144          6.7         3.3          5.7         2.5   Iris-virginica
137          6.4         3.1          5.5         1.8   Iris-virginica
94           5.6         2.7          4.2         1.3  Iris-versicolor
69           5.6         2.5          3.9         1.1  Iris-versicolor

In [42]:
iris_test_df = iris.drop(iris_train_df.index).copy()
iris_test_df

SepalLength  SepalWidth  PetalLength  PetalWidth            Name
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[144 rows x 5 columns]

In [13]:
def mean_std_table(dataframe):
    mean_std_dict = {}
    for each_column, each_dtype in zip(iris.columns, iris.dtypes):
        if each_dtype == 'float64':
            column_mean = iris[each_column].mean()
            column_std = iris[each_column].std()
            mean_std_dict[each_column] = column_mean, column_std
            dataframe[each_column] = (dataframe[each_column]- column_mean)/(column_std**2)
    return mean_std_dict

In [14]:
my_stats_dict = mean_std_table(iris)
my_stats_dict

{'SepalLength': (5.843333333333335, 0.8280661279778629),
 'SepalWidth': (3.0540000000000007, 0.4335943113621737),
 'PetalLength': (3.7586666666666693, 1.7644204199522617),
 'PetalWidth': (1.1986666666666672, 0.7631607417008414)}

In [15]:
iris

SepalLength  SepalWidth  PetalLength  PetalWidth            Name
0      -1.084061    2.372290    -0.757639   -1.714701     Iris-setosa
1      -1.375736   -0.287228    -0.757639   -1.714701     Iris-setosa
2      -1.667412    0.776579    -0.789761   -1.714701     Iris-setosa
3      -1.813249    0.244676    -0.725518   -1.714701     Iris-setosa
4      -1.229898    2.904193    -0.757639   -1.714701     Iris-setosa
..           ...         ...          ...         ...             ...
145     1.249343   -0.287228     0.462978    1.890979  Iris-virginica
146     0.665992   -2.946745     0.398735    1.204183  Iris-virginica
147     0.957668   -0.287228     0.462978    1.375882  Iris-virginica
148     0.520155    1.840386     0.527221    1.890979  Iris-virginica
149     0.082641   -0.287228     0.430856    1.032484  Iris-virginica

[150 rows x 5 columns]

In [16]:
def my_hot_encoding(dataframe, feature_list_to_encode):
    encoding_dict = {}
    for each_feature in feature_list_to_encode:
        feature_dict = {}
        for index_type, each_type in enumerate(dataframe[each_feature].unique()):
            feature_dict[each_type] = index_type
        encoding_dict[each_feature] = feature_dict
    for each_feature in feature_list_to_encode:
        dataframe[each_feature] = dataframe[each_feature].map(lambda x: encoding_dict[each_feature][x])
    else:
        dataframe[each_feature] = dataframe[each_feature].astype(int)
    return encoding_dict
        
            

In [17]:
my_discrete_dict = my_hot_encoding(iris, ['Name'])
my_discrete_dict

{'Name': {'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}}

In [18]:
iris.dtypes

SepalLength    float64
SepalWidth     float64
PetalLength    float64
PetalWidth     float64
Name             int64
dtype: object

In [19]:
iris.sample(10)

SepalLength  SepalWidth  PetalLength  PetalWidth  Name
97      0.520155   -0.819131     0.173884    0.173988     1
26     -1.229898    1.840386    -0.693396   -1.371303     0
4      -1.229898    2.904193    -0.757639   -1.714701     0
116     0.957668   -0.287228     0.559342    1.032484     2
100     0.665992    1.308483     0.719950    2.234377     2
60     -1.229898   -5.606263    -0.083088   -0.341109     1
54      0.957668   -1.351035     0.270249    0.517387     1
74      0.811830   -0.819131     0.173884    0.173988     1
68      0.520155   -4.542456     0.238127    0.517387     1
145     1.249343   -0.287228     0.462978    1.890979     2

In [20]:
iris_train_df = iris.sample(frac=1)

In [21]:
iris_train_df.dtypes, iris.dtypes

(SepalLength    float64
 SepalWidth     float64
 PetalLength    float64
 PetalWidth     float64
 Name             int64
 dtype: object,
 SepalLength    float64
 SepalWidth     float64
 PetalLength    float64
 PetalWidth     float64
 Name             int64
 dtype: object)

In [22]:
iris_train_df.columns

Index(['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Name'], dtype='object')

In [23]:
features = ['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth']
labels = ['Name']

In [24]:
iris_tr = torch.tensor(iris.to_numpy())

In [81]:
from torch.utils import data

# Parameters
params = {'batch_size': 7,
          'shuffle': True,
          'num_workers': 2}
training_generator = data.DataLoader(iris_tr, **params)

In [82]:
dummy = training_generator.__iter__().next()
dummy

tensor([[-1.9591, -4.0106, -0.7898, -1.5430,  0.0000],
        [ 0.3743, -2.4148,  0.5915,  0.3457,  2.0000],
        [-0.2090, -2.4148, -0.0831, -0.3411,  1.0000],
        [-2.2508, -0.2872, -0.8540, -1.8864,  0.0000],
        [-1.3757,  0.2447, -0.7255, -1.8864,  0.0000],
        [ 2.5619, -0.2872,  0.9127,  1.5476,  2.0000],
        [-1.0841,  1.8404, -0.7255, -1.7147,  0.0000]], dtype=torch.float64)

In [299]:
dummy[:,-1].type(torch.IntTensor)

tensor([0, 2, 1, 0, 0, 2, 0], dtype=torch.int32)

In [276]:
# w = torch.rand(dim, requires_grad=True)
w = torch.rand(4,3, requires_grad=True)
b = torch.rand(1, requires_grad=True)
w, b

(tensor([[0.3894, 0.1339, 0.0220],
         [0.9231, 0.3532, 0.4501],
         [0.5169, 0.4078, 0.2602],
         [0.6727, 0.2713, 0.5925]], requires_grad=True),
 tensor([0.0497], requires_grad=True))

In [277]:
sample_batch = dummy[:,0:-1]
sample_batch, w

(tensor([[-1.9591, -4.0106, -0.7898, -1.5430],
         [ 0.3743, -2.4148,  0.5915,  0.3457],
         [-0.2090, -2.4148, -0.0831, -0.3411],
         [-2.2508, -0.2872, -0.8540, -1.8864],
         [-1.3757,  0.2447, -0.7255, -1.8864],
         [ 2.5619, -0.2872,  0.9127,  1.5476],
         [-1.0841,  1.8404, -0.7255, -1.7147]], dtype=torch.float64),
 tensor([[0.3894, 0.1339, 0.0220],
         [0.9231, 0.3532, 0.4501],
         [0.5169, 0.4078, 0.2602],
         [0.6727, 0.2713, 0.5925]], requires_grad=True))

In [279]:
y_hat = torch.matmul(sample_batch, w.type(torch.float64))
y_hat, y_hat.shape

(tensor([[-5.9113, -2.4194, -2.9679],
         [-1.5452, -0.4678, -0.7200],
         [-2.5830, -1.0073, -1.3153],
         [-2.8519, -1.2628, -1.5186],
         [-1.9537, -0.9054, -1.2265],
         [ 2.2451,  1.0336,  1.0814],
         [-0.2516, -0.2562, -0.4002]], dtype=torch.float64,
        grad_fn=<MmBackward>),
 torch.Size([7, 3]))

In [280]:
import torch.nn as nn
criterion = nn.CrossEntropyLoss()

In [281]:
# https://stackoverflow.com/questions/49390842/cross-entropy-in-pytorch
loss = criterion(y_hat, y_actual.type(torch.LongTensor))
loss

tensor(1.7676, dtype=torch.float64, grad_fn=<NllLossBackward>)

In [282]:
y_actual

tensor([0, 2, 1, 0, 0, 2, 0])

In [290]:
https://pytorch.org/docs/stable/nn.html?highlight=crossentropyloss#torch.nn.CrossEntropyLoss
my_sum = 0
for index, value in enumerate(y_actual.type(torch.IntTensor)):
    my_sum += y_hat[index, value]*-1 + torch.log(torch.exp(y_hat[index]).sum())
print(my_sum/7)

tensor(1.7676, dtype=torch.float64, grad_fn=<DivBackward0>)


In [376]:
def my_loss(y_hat, y_actual):
    my_sum = 0
    for index, value in enumerate(y_actual.type(torch.IntTensor)):
        my_sum += y_hat[index, value]*-1 + torch.log(torch.exp(y_hat[index]).sum())
    return my_sum/y_hat.shape[0]

In [379]:
step_size = torch.tensor(.0001)
num_epochs = 5000
minibatch_size = 20
w = torch.rand(4,3, requires_grad=True, dtype=torch.float64)
b = torch.rand(1, requires_grad=True, dtype=torch.float64)
w, b
# optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

(tensor([[0.6673, 0.3759, 0.0758],
         [0.5282, 0.0964, 0.6912],
         [0.2048, 0.8031, 0.7101],
         [0.7284, 0.2818, 0.9685]], dtype=torch.float64, requires_grad=True),
 tensor([0.3194], dtype=torch.float64, requires_grad=True))

In [380]:
epochs = 5000
loss_arr = []
for i in range(epochs):
    for batch in training_generator:
        y_hat = torch.matmul(batch[:,:-1], w) + b
#         loss = criterion(y_hat, batch[:,-1].type(torch.LongTensor)) #average loss per batch
        loss = my_loss(y_hat, batch[:,-1].type(torch.LongTensor))
        loss_arr.append(loss)
        loss.backward()
        w.data -= step_size * w.grad.data
        b.data -= step_size * b.grad.data
        w.grad.data.zero_()
        b.grad.data.zero_()
    if i % 25 == 0:
        print(loss)

tensor(0.8294, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.9489, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(1.0555, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(1.1955, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.7960, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.5790, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.9364, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.6926, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.3345, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.5476, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.5908, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.3524, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.7636, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.7115, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.2724, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.7149, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.3455, dtype=torch.float64, grad

KeyboardInterrupt: 